### ISSUE TITLE
Cancel download

### ISSUE THREAD

**Issue by Iaiao** [JaGoLi/ytdl-gui#3]
If you download a very long video or livestream, the only way to stop ytdl-gui is to kill its process, but it will also stop youtube-dl which should do some things before exiting (e.g. write moov atom and rename livestream .mp4.part to .mp4), so there are currently no good way to stop it.

**Comment by JaGoLi** [comment]
I see this is an issue. I just recently decided to block the user from being able to close the progress window while there is a download, because I wasn't sure how well my app could handle parallel downloads. The old behavior meant that once the window was closed, the download would still be going on in the background. The good thing is a lot of the work has been done already. When you click to close the download window, I will now instead be implementing a popup to ask if you really want to cancel.

**Comment by JaGoLi** [comment]
Ability to cancel download in beta branch.
