### ISSUE TITLE
FLAC support

### ISSUE THREAD

**Issue by sanjayen** [JaGoLi/ytdl-gui#44]
Thank you for creating this GUI. I have to struggle with the command line of youtube-dl. I installed v2.5 using Flatpak. But I see OGG instead of FLAC as an option for audio downloads. The screenshot shows that ytdl-gui used to have FLAC support earlier. Any reason this was replaced with OGG? Can you please add it back?

Keep up the good work.

**Comment by JaGoLi** [comment]
I removed FLAC support because it is fake, and not real lossless audio. The flac option basically took a lossy audio file from youtube and re-encoded it to FLAC. If you want the best audio possible, just use the `default` checkbox when the audio tab is selected. Youtube-dl defaults with the best format and you will not have any other losses with re-encoding.

**Comment by sanjayen** [comment]
Thank you. Will use the default option.
